[project]
name = "selenium-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "dotenv>=0.9.9",
    "psycopg2-binary>=2.9.11",
    "pyrefly>=0.46.0",
    "selenium>=4.39.0",
    "sqlalchemy>=2.0.45",
]

[tool]

[tool.pyrefly]
project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]
